# fly.toml app configuration file generated for game-uidesign-by-derrick-co-mantey on 2024-01-17T23:46:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "game-uidesign-by-derrick-co-mantey"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
